FROM metocean/swan:comp-py3-gf
LABEL maintainer "Henrique Rapizo <h.rapizo@metocean.co.nz>"

ARG ftn
ARG default_mode

# Set required environment variables
ENV FTN=$ftn
ENV DEFAULT_MODE=$default_mode
ENV INSTALL_SCRIPTS="/tmp/install_scripts"
ENV SWAN_TEST="/home/metocean"
ENV SWAN_SRC="/source/swan-src/swan_src"

# Compile and install model
COPY swan_src $SWAN_SRC
COPY install_scripts/install_swan.sh $INSTALL_SCRIPTS/
RUN ./$INSTALL_SCRIPTS/install_swan.sh &&\
    rm -f $INSTALL_SCRIPTS/install_swan.sh

# copy entrypoint
COPY install_scripts/entrypoint.sh $INSTALL_SCRIPTS/
