FROM metocean/ifort:v19-python_3.7-buster
# FROM metocean/ifort:2022 # (currently breaking running model on mpi)
FROM python:3.7-slim-buster
LABEL maintainer "MetOcean waves team"

ARG mpich_version
ARG hdf5_version
ARG netcdf_version
ARG netcdf_fortran_version

# copy compiler(s)
COPY --from=0 /opt/intel /opt/intel
# COPY --from=0 /opt/intel/oneapi /opt/intel/oneapi #(v2022)

ARG USER_ID=1001
ARG GROUP_ID=1001
ARG USER_NAME=metocean

RUN apt -y update &&\
    apt -y upgrade &&\
    apt install -y vim \ 
    sudo \ 
    wget \
    build-essential \
    zlib1g \
    zlib1g-dev \
    m4 \
    procps \
    gdb \
    less &&\
    apt -y clean

RUN adduser -u $USER_ID $USER_NAME --disabled-password &&\
    chmod 666 /etc/sudoers &&\
    echo "$USER_NAME ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers &&\
    chmod 440 /etc/sudoers

# Set required environment variables
ENV MPICH_VERSION=$mpich_version
ENV HDF5_VERSION=$hdf5_version
ENV NETCDF_VERSION=$netcdf_version
ENV NETCDF_FORTRAN_VERSION=$netcdf_fortran_version

# we separate the build of libs for allowing caching
ADD install_scripts/install_mpich.sh /tmp/
RUN  echo "----------------------------------------" &&\
     echo "---------- Installing mpich ------------" &&\
     echo "----------------------------------------" &&\
     cd /tmp && ./install_mpich.sh
ADD install_scripts/install_hdf5.sh /tmp/
RUN  echo "----------------------------------------" &&\
     echo "---------- Installing hdf5 -----------" &&\
     echo "----------------------------------------" &&\
     cd /tmp && ./install_hdf5.sh
ADD install_scripts/install_netcdf4.sh /tmp/
RUN  echo "----------------------------------------" &&\
     echo "---------- Installing netcdf4 ----------" &&\
     echo "----------------------------------------" &&\
     cd /tmp && ./install_netcdf4.sh &&\
     rm -rf /tmp/*

CMD ["/bin/bash"]