FROM metocean/swan:base
MAINTAINER Rafael Guedes <r.guedes@metocean.co.nz>

ARG ftn
ARG mode

# Set required environment variables
ENV FTN=$ftn
ENV MODE=$mode
ENV INSTALL_SCRIPTS="/tmp/install_scripts"
ENV SWAN_TEST="/home/metocean"
ENV SWAN_SRC="/source/swan-src/swan_src"

# Compile and install model
COPY swan_src $SWAN_SRC
COPY install_scripts/install_swan.sh $INSTALL_SCRIPTS/
RUN sh $INSTALL_SCRIPTS/install_swan.sh &&\
    rm -f $INSTALL_SCRIPTS/install_swan.sh

# Copy SWAN test data
COPY test_data/swan_test_data.tar.gz $SWAN_TEST/

# copy entrypoint
COPY install_scripts/entrypoint.sh $INSTALL_SCRIPTS/