FROM metocean/swan:model
LABEL maintainer "Rafael Guedes <r.guedes@metocean.co.nz>"

# Compile and install model reference src to be compared with
COPY swan_src $SWAN_SRC
COPY install_scripts/install_swan-ref.sh $INSTALL_SCRIPTS/
RUN sh $INSTALL_SCRIPTS/install_swan-ref.sh &&\
    rm -f $INSTALL_SCRIPTS/install_swan-ref.sh

# copy entrypoint
COPY install_scripts/entrypoint.sh $INSTALL_SCRIPTS/

RUN yum -y install nco
RUN pip install --upgrade --no-cache-dir ipython==5 \
                                         nco        \
                                         xarray                              
RUN pip install --upgrade --no-cache-dir netCDF4

# copy since mounting does not work with bob
COPY tests/run_tinyapp.py /usr/local/bin/
COPY tests/tinyapp.tar.gz /home/metocean
COPY tests/test_src.py /usr/local/bin/
COPY tests/conftest.py /usr/local/bin/

# install docker to run other containers in the test
# RUN wget -qO- https://get.docker.com/ | sh #(last stable version)
# RUN yum -y install docker
# install gfrotran to compile wavespectra
#RUN yum -y install gcc-gfortran
# install wavespectra for model comparison
#RUN pip install --upgrade --no-cache-dir wavespectra[extra]==0.2.1

# install pytest 
RUN pip install --upgrade --no-cache-dir pytest