version: '2'

services:

  # Install ifort and libraries required for static model compilation
  comp:
    image: metocean/swan:comp
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        mpich_version: 3.2
        hdf5_version: 1.10.1
        netcdf_version: 4.4.1
        netcdf_fortran_version: 4.4.4

  # Build and install model binaries
  model:
    image: metocean/swan:model
    build:
      context: ./
      dockerfile: Dockerfile-model
      args:
        ftn: msl
        default_mode: mpi
    depends_on:
      - comp

  test_model:
    image: metocean/swan:model
    command: python /source/swan-src/tests/run_tinyapp.py
    volumes:
      - /source/swan-src/tests:/source/swan-src/tests
      - /source/swan/bin/exe/swan.exe:/source/swan/bin/exe/swan.exe
