FROM metocean/ifort:2022
FROM python:3.7-slim-buster
LABEL maintainer "MetOcean waves team"

ARG mpich_version
ARG hdf5_version
ARG netcdf_version
ARG netcdf_fortran_version

# copy compiler(s)
COPY --from=0 /opt/intel /opt/intel

ARG USER_ID=1001
ARG GROUP_ID=1001
ARG USER_NAME=metocean

RUN apt -y update &&\
    apt install -y vim sudo wget &&\
    apt -y upgrade &&\
    apt -y clean

RUN adduser -u $USER_ID $USER_NAME --disabled-password &&\
    chmod 666 /etc/sudoers &&\
    echo "$USER_NAME ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers &&\
    chmod 440 /etc/sudoers

# Set required environment variables
ENV MPICH_VERSION=$mpich_version
ENV HDF5_VERSION=$hdf5_version
ENV NETCDF_VERSION=$netcdf_version
ENV NETCDF_FORTRAN_VERSION=$netcdf_fortran_version

# zlib used to build hdf5/netcdf/swan
RUN apt install -y build-essential zlib1g zlib1g-dev m4 &&\
    apt -y clean

# for debugging
RUN apt-get install -y gdb less

ADD install_scripts/install_required.sh /tmp/
RUN cd /tmp && ./install_required.sh &&\
    rm -rf /tmp/*

CMD ["/bin/bash"]