version: '2'

services:

  # Install ifort and libraries required for static model compilation
  comp:
    image: metocean/swan:comp
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        mpich_version: 3.2
        hdf5_version: 1.10.1
        netcdf_version: 4.4.1
        netcdf_fortran_version: 4.4.4

  # Build and install model binaries
  model:
    image: metocean/swan:model
    build:
      context: ./
      dockerfile: Dockerfile-model
      args:
        ftn: msl
        default_mode: mpi
    depends_on:
      - comp
  
  # Build test image
  test:
    image: metocean/swan:modeltest-4120B
    build:
      context: ./
      dockerfile: Dockerfile-test
      args:
        ftnref: stock
        default_mode: mpi
    depends_on:
      - model

  test_model: # legacy
    image: metocean/swan:modeltest
    command: python /usr/local/bin/run_tinyapp.py
    
  test_src:
    image: metocean/swan:modeltest
    command: bash -c "cd /usr/local/bin && pytest -v -s test_src.py --models=4120,4120"
