FROM metocean/swan:model
LABEL maintainer "Rafael Guedes <r.guedes@metocean.co.nz>"

RUN yum -y install nco
RUN pip install --upgrade --no-cache-dir ipython==5 nco                                
RUN pip install --upgrade --no-cache-dir netCDF4

# copy since mounting does not work with bob
COPY tests/run_tinyapp.py /usr/local/bin/
COPY tests/tinyapp.tar.gz /home/metocean
COPY tests/testsrc.py /usr/local/bin/
COPY tests/testsrc_simple.py /usr/local/bin/

# install docker to run other containers in the test
# RUN wget -qO- https://get.docker.com/ | sh #(last stable version)
# RUN yum -y install docker
# install gfrotran to compile wavespectra
RUN yum -y install gcc-gfortran
# install wavespectra to compare model results
RUN pip install --upgrade --no-cache-dir wavespectra[extra]==0.2.1

# install pytest 
RUN pip install --upgrade --no-cache-dir pytest